# FROM verlai/verl:sgl056.latest
FROM nvcr.io/nvidia/nemo:25.11.01

# 1. Set up workspace directories and symlinks
RUN git config --global --add safe.directory '*'
RUN mkdir -p /root/myCodeLab && \
    ln -s /public /root/myCodeLab/public && \
    ln -s /public/lichang93/stCodeLab /root/myCodeLab/host

# 2. Install your project's Python dependencies
# RUN rm ~/.config/pip/pip.conf && pip config set global.index-url https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple
RUN pip config set global.index-url https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple
# RUN chown -R root:root /usr/lib

# 3. Log in to Weights & Biases
RUN wandb login df3cecbfc0874c8a352c40820becf4a15575614e

# 4. Install Dev Deps
RUN apt-get update && apt-get install pdsh tmux htop vim -y
# libnuma-dev

RUN pip install --no-cache-dir --upgrade-strategy "only-if-needed" gpustat codetiming tensordict mathruler pylatexenc

COPY mbridge /root/myCodeLab/mbridge/
RUN cd /root/myCodeLab/mbridge/ && \
    pip3 install --no-cache-dir --no-deps . && \
    cd .. && rm -rf mbridge

COPY verl /root/myCodeLab/host/verl/
RUN cd /root/myCodeLab/host/verl && \
    # pip3 install -e .[vllm] && \
    # pip3 install -e .[sglang] && \
    pip3 install --no-deps -e . && \
    cd /root/myCodeLab/host/ && rm -rf verl

## Fragile Configs
# vllm 0.12 uses openai harmony gpt oss encode
RUN mkdir -p /root/tiktoken_cache
COPY o200k_base.tiktoken /root/tiktoken_cache/o200k_base.tiktoken
ENV TIKTOKEN_ENCODINGS_BASE=/root/tiktoken_cache

# .bashrc alias
COPY to_append.sh /tmp/to_append.sh
RUN echo "" >> /root/.bashrc && \
    cat /tmp/to_append.sh >> /root/.bashrc && \
    rm /tmp/to_append.sh
COPY .tmux.conf /root/.tmux.conf
RUN ln -s /usr/local/lib/python3.12/dist-packages /root/myCodeLab/dist-packages

# Missing deps
RUN pip install --no-cache-dir --upgrade-strategy "only-if-needed" torchdata
# VLLM 0.12.0 (was 0.10.0)
RUN rm -rf /opt/vllm && \
    pip install setuptools_scm

COPY vllm /opt/vllm
RUN cd /opt/vllm && \
    MAX_JOBS=64 NVCC_THREADS=1 pip install --no-deps --no-build-isolation --no-cache-dir -e .

# Set the final working directory and default command
WORKDIR /root/myCodeLab
CMD ["/bin/bash"]

# docker build --network host -t registry.cn-sh-01.sensecore.cn/jd-ccr/verl:0d6_vllm_yan .
# docker run -itd -v /mnt/public:/public --name verlvllm --network host registry.cn-sh-01.sensecore.cn/jd-ccr/verl:devnow
# dbash verlvllm
# drm verlvllm
# docker build -t registry.cn-sh-01.sensecore.cn/jd-ccr/verl:devnow .
# docker run -itd -v /mnt/public:/public --name verlvllm --network host registry.cn-sh-01.sensecore.cn/jd-ccr/verl:devnow
# dbash verlvllm
# docker commit verlvllm registry.cn-sh-01.sensecore.cn/jd-ccr/verl:devnow
# docker push registry.cn-sh-01.sensecore.cn/jd-ccr/verl:devnow

# VLLM
# docker build -f Dockerfile.mydev --provenance=false --network host -t registry.cn-xn-01.sensecore.cn/ccr-xn/verl:vllm012.dev .
# docker build -f Dockerfile.mydev --provenance=false --network host -t registry.cn-xn-01.sensecore.cn/ccr-xn/verl:vllm011mcore14.dev .
# docker build -f Dockerfile.mydev --provenance=false --network host -t registry.cn-xn-01.sensecore.cn/ccr-xn/verl:vllm011mcore14blbnojit.dev .
# docker run -itd -v /mnt/public:/public --name vrl --network host registry.cn-xn-01.sensecore.cn/ccr-xn/verl:vllm011mcore14.dev
# docker run -itd -v /mnt/public:/public --name vrl --network host registry.cn-xn-01.sensecore.cn/ccr-xn/verl:vllm012.dev
# docker run --entrypoint /bin/bash -itd -v /mnt/public:/public --name vrl --network host registry.cn-xn-01.sensecore.cn/ccr-xn/verl:vllm0113.dev

# DOCKER_BUILDKIT=0 docker build -f Dockerfile.mydev --provenance=false --network host -t registry.cn-hangzhou.aliyuncs.com/spacegoing/verl:vllm012blbharm.dev .

# SGLANG
# docker build -f Dockerfile.mydev --provenance=false --network host -t registry.cn-xn-01.sensecore.cn/ccr-xn/verl:sgl055.dev .
# docker run -itd -v /mnt/public:/public --name vrl --network host registry.cn-xn-01.sensecore.cn/ccr-xn/verl:sgl055.dev
# docker build -f Dockerfile.mydev --provenance=false --network host -t registry.cn-xn-01.sensecore.cn/ccr-xn/verl:sgl056.dev .
# docker run -itd -v /mnt/public:/public --name vrl --network host registry.cn-xn-01.sensecore.cn/ccr-xn/verl:sgl056.dev
